version: '3.1'

services:
  db:
    image: postgres:15-alpine3.18
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: news_feed_bot
      PGDATA: /var/lib/postgresql/data/
    ports:
      - "5432:5432"
    volumes:
      - ./.data/pgdata:/var/lib/postgresql/data/

volumes:
  db: